---
- name: Add users with loop
  hosts: nodes
  vars_files:
    - vars/users_encrypted.yaml
    - vars/users_settings.yaml
  tasks:
    - name: Loop users and creating them
      ansible.builtin.user:
        name: "{{ users_list_item.name }}"
        password: "{{ users_list_item.password | password_hash('sha512') }}"
        comment: "{{ users_comment }}"
        uid: "{{ users_list_item.uid }}"
      no_log: true
      loop: "{{ users_list }}"
      loop_control:
        loop_var: users_list_item
        pause: "{{ create_user_pause }}"
