---
# handlers file for role_generate_certificate
- name: Certificate testing
  community.crypto.x509_certificate:
    csr_path: "{{ nginx_csr_dir }}/{{ nginx_csr_name }}"
    path: "{{ nginx_crt_dir }}/{{ nginx_crt_name }}"
    privatekey_path: "{{ nginx_pem_dir }}/{{ nginx_pem_name }}"
    provider: selfsigned