---
# handlers file for role_generate_certificate
- name: Certificate testing
  community.crypto.x509_certificate_info:
    path: "{{ nginx_crt_dir }}/{{ nginx_crt_name }}"
  register: cert_info
  ignore_errors: true
  failed_when: cert_info.expired