---
# vars file for role_install_nginx

# roles/role_install_nginx vars
# Nginx port for HTTP:
nginx_port_no_tls: 80
# Nginx port for HTTPS:
nginx_port_tls: 443
# nginx.conf path
nginx_config_path: "/etc/nginx/nginx.conf"
# sites.conf path
nginx_config_site_path: "/etc/nginx/conf.d/sites.conf"
# index.html path
nginx_index_html_path: "/usr/share/nginx/html/index.html"
# Folders for certificate crt, csr and private key location:
nginx_crt_dir: /etc/ssl/crt
nginx_pem_dir: /etc/ssl/private
nginx_csr_dir: /etc/ssl/csr
# Names of certificate's crt, csr and private key:
nginx_crt_name: nginx.crt
nginx_pem_name: nginx.pem
nginx_csr_name: nginx.csr